// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Definition = {
  word: string;
  phonetic: string | null;
  phonetics: Array<Phonetic>;
  meanings: Array<Meaning>;
  license: License;
  sourceUrls: Array<string> | null;
};

export type DefinitionEntry = {
  definition: string;
  synonyms: Array<string>;
  antonyms: Array<string>;
  example: string | null;
};

export type License = { name: string; url: string };

export type Meaning = {
  partOfSpeech: string;
  definitions: Array<DefinitionEntry>;
};

export type Phonetic = {
  text: string | null;
  audio: string;
  sourceUrl: string | null;
};
