// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Colour =
  | 'blue'
  | 'cambridge'
  | 'melon'
  | 'mikado'
  | 'mindaro'
  | 'slate'
  | 'sunset'
  | 'tickle'
  | 'tiffany'
  | 'wisteria';

export type NoteFormat = 'full' | 'slim';
