// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: string, title: string, content: string, colour: string, userId: string, createdAt: string, isArchived: boolean, isFavourite: boolean, isPublic: boolean, lastUpdate: string, name: string, fullNote: boolean, noteFormat: string, };
