// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { Colour } from './Enums';

export type PartialNote = {
  id: string;
  title: string;
  content: string;
  colour: Colour;
  createdAt: string;
};
