// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteFormat } from "./Enums";

export type UserPreferences = { noteFormat: NoteFormat, fullNote: boolean, };
