// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PartialNote = { id: string, title: string, content: string, colour: string, createdAt: string, };
